### ISSUE TITLE
com.intellij.execution.process.ProcessNotCreatedException

### ISSUE THREAD

**Issue by nickfan** [hoperuin/go-cross-build#1]
```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "null/bin/go" (in directory "/mydevProject"): error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:412)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:45)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:38)
	at me.shifei.go.plugin.cross.build.Helper$1.run(Helper.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot run program "null/bin/go" (in directory "/Users/user/go/src/github.com/user/mydevProject"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:443)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:408)
	... 16 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 19 more
```

**Comment by hoperuin** [comment]
没有GOROOT环境变量吗？

**Comment by nickfan** [comment]
![image](https://user-images.githubusercontent.com/100613/66545655-c3c5e600-eb6d-11e9-89c7-ac891c4c64d7.png)

有的哦。

**Comment by hoperuin** [comment]
已解决,下载最新即可。
